# https://dependabot.com/docs/config-file/
# version: 1
# update_configs:
#   - package_manager: 'javascript'
#     directory: '/packages/slant-api-js'
#     update_schedule: 'daily'
#     commit_message:
#       prefix: 'fix'
#       prefix_development: 'chore'
#       include_scope: true
